### ISSUE TITLE
About the scaffold databases

### ISSUE THREAD

**Issue by NECCCCCCC** [LPDI-EPFL/masif_seed#2]
Hello, I am trying to run the seed refinement and grafting, but I can't find the scaffold databases. I read the paper which said a database of 1300 monomeric scaffolds was used for RBD and PDL1 designs. Can you provide this scaffold database? Looking forward to your reply.

**Comment by bud-graziano** [comment]
Hi, we now added a link to the scaffold database to the repo. You can find the scaffolds that were used here: https://zenodo.org/record/7643697#.ZD0aMOxBw-Q
