### ISSUE TITLE
DockerFile invalid python sklearn

### ISSUE THREAD

**Issue by slieped** [LPDI-EPFL/masif_seed#4]
The DockerFile to build pip3 install sklearn.
However, this is only a empty-repo from scikit-learn to prevent malicious attacks.
Check here:  https://pypi.org/project/sklearn/
and the correct one here: https://pypi.org/project/scikit-learn/

PS. thanks for this great tool and congratz on the publication!

Victor Montal

**Comment by LDAIprotein** [comment]
+1

**Comment by bud-graziano** [comment]
Hi Victor,
thanks for opening a ticket! I updated to dockerfile to use the correct scikit-learn repo.
