### ISSUE TITLE
Manually assign binding site (patch) on target protein

### ISSUE THREAD

**Issue by rguiscard** [LPDI-EPFL/masif_seed#5]
Thanks for this wonderful software to find binding helix to a target protein. The protocol uses masif_site to predict binding patch on target protein. Is it possible to assign a binding site (patch) manually ? For example, I would like to design a binder to a patch of Covid RBD which mutates less frequently. Masif_site may not work in this case. I guess it is set somewhere in iface npy, but I cannot figure out how to set it correctly. Thanks for your help.

**Comment by bud-graziano** [comment]
Hi,
when you run the seed search, you can set a target residue (or technically rather a target atom). This can be done in the `params_peptides.py` file (see: `masif_seed_search/data/masif_targets/targets/template/params_peptides.py`).

```
# Target a specific residue.
# cutoff: the maximum distance of the center of the patch to this residue.
# resid: the residue number in the PDB chain for this residue.
#params['target_residue'] = {'cutoff': 10.0, 'resid': 100, 'chain': 'A', 'atom_id': 'CA'}
```

Uncomment the last line and set the residue and chain ID which will be the center of the targeted patch.
